modLoader="javafml"
loaderVersion="[39,)"
license="LGPL-3.0-or-later"

[[mods]]
modId="qmpcompat"
version="${file.jarVersion}"
displayName="QNG ModPack Compatibility Tweaks"
description='''
Miscellaneous tweaks to the QNG ModPack.
'''

    [[dependencies.qmpcompat]]
        modId="enhancedfarming"
        mandatory=true
        versionRange="[1.2.3,)"
        ordering="AFTER"
    
    [[dependencies.qmpcompat]]
        modId="cookingforblockheads"
        mandatory=false
        versionRange="[0,)"
        ordering="AFTER"
