modLoader="javafml"
loaderVersion="[39,)"
license="cc0-1.0"

[[mods]]
modId="qmpcompat"
version="${file.jarVersion}"
displayName="[QMP] QNG ModPack Compatibility Tweaks"
description='''
Miscellaneous tweaks to the QNG ModPack.
'''

    [[dependencies.qmpcompat]]
        modId="enhancedfarming"
        mandatory=false
        versionRange="[1.2.3,)"
        ordering="AFTER"
    
    [[dependencies.qmpcompat]]
        modId="cookingforblockheads"
        mandatory=false
        versionRange="[0,)"
        ordering="AFTER"
